package com.cwiczenia.ksiegowanie.entity;

public enum CostNoForConstructionSiteNo {
    MATERIALY_PODSTAWOWE, PLACE, TRANSPORT_WLASNY, TRANSPORT_OBCY, ZURAWIE,
    ZAPLECZE_TOALETY, MATERIALY_POMOCNICZE_PALIWO,OCHRONA,SZALUNKI, KOSZTY_INNE
}
